#ifndef __RTWLAN_CONFIG_H
#define __RTWLAN_CONFIG_H
#include "FreeRTOSConfig.h"
#define CONFIG_PLATFOMR_CUSTOMER_RTOS
#define DRV_NAME "rtl8189ftv"
#define DRIVERVERSION "a05b84ef4f982c9b585df42799d158274f604318"


#define CONFIG_DEBUG						1

#define CONFIG_THROUGHPUT_LEVEL 3
#define CONFIG_TX_BUS_AGG_NUM	8
#define CONFIG_RX_BUS_AGG_NUM	8  
#define MAX_TX_SKB_DATA_NUM	150
#define CONFIG_ADDRESS_ALIGNMENT			1
#define CONFIG_USE_INDEPENDENT_TX_BUS_AGG_DATA	1
#endif
